# Generated by Django 3.0.5 on 2020-05-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=100)),
                ('puzzle_name', models.CharField(max_length=100)),
                ('puzzle_ans', models.CharField(max_length=100)),
                ('unlocks_at', models.IntegerField(default=0)),
            ],
        ),
    ]
