# Generated by Django 3.0.5 on 2020-05-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunt20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('puzzle_id', models.CharField(max_length=100)),
                ('team_ans', models.CharField(max_length=100)),
                ('eventdatetime', models.DateTimeField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=400)),
                ('is_testsolver', models.BooleanField(default=False)),
                ('member1', models.EmailField(max_length=254, null=True)),
                ('member2', models.EmailField(max_length=254, null=True)),
                ('member3', models.EmailField(max_length=254, null=True)),
                ('member4', models.EmailField(max_length=254, null=True)),
                ('member5', models.EmailField(max_length=254, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
