# Generated by Django 3.0.5 on 2020-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt20', '0002_submission_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='in_round',
            field=models.IntegerField(default=1),
        ),
    ]
