# Generated by Django 3.0.5 on 2020-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt20', '0004_auto_20200523_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('puzzle_name', models.CharField(max_length=100)),
                ('team_question', models.TextField()),
                ('hq_ans', models.TextField(default='(pending...)')),
                ('eventdatetime', models.DateTimeField()),
                ('answered', models.BooleanField()),
                ('refunded', models.BooleanField(default=False)),
            ],
        ),
    ]
