# Generated by Django 3.0.5 on 2020-06-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt20', '0005_hintrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='puzzle_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='puzzle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hunt20.Puzzle'),
        ),
    ]
