# Generated by Django 3.0.5 on 2020-06-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt20', '0006_auto_20200602_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member5',
        ),
    ]
