# Generated by Django 3.0.5 on 2020-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt20', '0007_auto_20200603_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.CharField(default='DNE', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='member1',
            field=models.CharField(default='DNE', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='member2',
            field=models.CharField(default='DNE', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='member3',
            field=models.CharField(default='DNE', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='member4',
            field=models.CharField(default='DNE', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='member5',
            field=models.CharField(default='DNE', max_length=100),
        ),
    ]
